---
- name: virtual server initial setup
  hosts: all
  remote_user: root
  # become: true
  # become_method: sudo
  # gather_facts: false

  # vars_prompt:
  #   - name: prompt_vars
  #     prompt: 'input: '
  #     default: 'prompt'
  #     confirm: no
  #     private: no

  # pre_tasks:
  #   - name: pre tasks
  #     debug:
  #       msg: >-
  #         start...
  #         pre tasks
  
  # post_tasks:
  # - name: post tasks
  #   debug:
  #     msg: >-
  #       post tasks
  #       ...end

  # tasks:
  #   - name: debug tasks
  #     shell: exit 1
  #     changed_when: false
  #     failed_when: false
  #     check_mode: false
  #     ignore_errors: yes
  
  #   - name: debug tasks
  #     shell: |
  #       st=""
  #       if [[ ${st} ]]; then
  #         echo true >/tmp/sample
  #       else
  #         echo false >/tmp/sample
  #       fi

  roles:
    # - base
    - extra
