---
- name: Distribute sudoers file for "Group"
  copy:
    src: "{{ group_files_dir }}/etc/sudoers.d/{{ item.name }}"
    dest: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ group.users }}"
  when: item.sudoers is defined and item.sudoers == 'enable'
  tags:
    - account

- name: Distribute sudoers file for "Host"
  copy:
    src: "{{ host_files_dir }}/etc/sudoers.d/{{ item.name }}"
    dest: "/etc/sudoers.d/{{ item.name }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ host.users }}"
  when: item.sudoers is defined and item.sudoers == 'enable'
  tags:
    - account
