---
- name: disable dns resolver for NetworkManager
  copy:
    src: etc/NetworkManager/conf.d/90-dns-none.conf
    dest: /etc/NetworkManager/conf.d/90-dns-none.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart NetworManager.service
  tags:
    - extra

- name: update the use nameserver
  copy:
    src: etc/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - extra

- name: update in nsswitch.conf
  set_fact:
    nsswitch_hosts: 'files dns'
  when: host.nsswitch_hosts_dns is defined and host.nsswitch_hosts_dns == 'enable'
  tags:
    - extra

- name: update name service switch configuration
  template:
    src: etc/nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: '0644'
  tags:
    - extra

- name: update hosts file
  copy:
    src: etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  tags:
    - extra

- name: update public zone file
  copy:
    src: etc/firewalld/zones/public.xml
    dest: /etc/firewalld/zones/public.xml
    owner: root
    group: root
    mode: '0644'
  tags:
    - extra
