---
- name: copy rpm file
  copy:
    src: "{{ item }}"
    dest: /tmp/
    owner: root
    group: root
    mode: '0644'
  loop:
    - sshpass-1.06-9.el8.x86_64.rpm
  tags:
    - '10'

- name: install package
  yum:
    name: /tmp/{{ item }}
    state: present
    disable_gpg_check: yes
  loop:
    - sshpass-1.06-9.el8.x86_64.rpm
  tags:
    - '10'
