---
- name: update hosts file
  copy:
    src: etc/hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  tags:
    - '11'

- name: update public zone file
  copy:
    src: etc/firewalld/zones/public.xml
    dest: /etc/firewalld/zones/public.xml
    owner: root
    group: root
    mode: '0644'
  tags:
    - '11'
