---
- name: copy rpm file
  copy:
    src: zabbix-agent-4.0.32-1.el8.x86_64.rpm
    dest: /tmp/
    owner: root
    group: root
    mode: '0644'

- name: install zabbix-agent
  yum:
    name: /tmp/zabbix-agent-4.0.32-1.el8.x86_64.rpm
    state: present

- name: copy configuration file
  template:
    src: etc/zabbix/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: '0644'
  notify: start zabbix-agent.service
