---
- name: update ntp server to connect
  copy:
    src: etc/chrony.conf
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart chronyd.service
  tags:
    - custom
