---
- name: start zabbix-agent.service
  systemd:
    name: zabbix-agent
    state: started
    enabled: yes

- name: restart zabbix-agent.service
  systemd:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: reload zabbix-agent.service
  systemd:
    name: zabbix-agent
    state: reloaded

- name: stop zabbix-agent.service
  systemd:
    name: zabbix-agent
    state: stopped
